2018-07-26T14:12:55+05:30 [undefined] error: uncaughtException: Callback was already called.
Error: Callback was already called.
    at C:\Users\Simato\Desktop\work\Otenro\source\node_modules\sails\node_modules\async\lib\async.js:43:36
    at C:\Users\Simato\Desktop\work\Otenro\source\node_modules\sails\lib\app\private\loadHooks.js:99:18
    at C:\Users\Simato\Desktop\work\Otenro\source\node_modules\sails-hook-orm\node_modules\async\lib\async.js:52:16
    at C:\Users\Simato\Desktop\work\Otenro\source\node_modules\sails-hook-orm\node_modules\async\lib\async.js:570:21
    at C:\Users\Simato\Desktop\work\Otenro\source\node_modules\sails-hook-orm\node_modules\async\lib\async.js:167:37
    at Array.async.auto._buildOntology (C:\Users\Simato\Desktop\work\Otenro\source\node_modules\sails-hook-orm\lib\initialize.js:385:16)
    at listener (C:\Users\Simato\Desktop\work\Otenro\source\node_modules\sails-hook-orm\node_modules\async\lib\async.js:605:42)
    at C:\Users\Simato\Desktop\work\Otenro\source\node_modules\sails-hook-orm\node_modules\async\lib\async.js:544:17
    at _arrayEach (C:\Users\Simato\Desktop\work\Otenro\source\node_modules\sails-hook-orm\node_modules\async\lib\async.js:85:13)
    at Immediate.taskComplete [as _onImmediate] (C:\Users\Simato\Desktop\work\Otenro\source\node_modules\sails-hook-orm\node_modules\async\lib\async.js:543:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
2018-07-26T14:13:13+05:30 [undefined] info: User Logged in! emailId:test@example.com
